## Airbnb Urban Pressure — Rome vs Copenhagen
### Data Visualization Project 2026

*April 2026*

In this notebook we explore Airbnb listing data for two European cities — 
Rome and Copenhagen — to understand how short-term rentals distribute 
across urban space and who controls the market.

The central question is: **how does Airbnb reshape urban neighbourhoods, 
and is the pressure concentrated or diffuse?**

We use data from [Inside Airbnb](https://insideairbnb.com/), an independent 
project that scrapes and publishes Airbnb listing data for cities worldwide. 
The Rome dataset was scraped in September 2025 (37,652 listings), 
the Copenhagen dataset in September 2025 as well (22,994 listings).

The analysis is structured in four parts:
1. Data loading and inspection
2. Cleaning and integration
3. Feature engineering (including the Urban Pressure Index)
4. Exploratory analysis to inform the visual system

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('/Users/andreamammano/Data Visualization/DataVisualisationPW_MESA/data/rome/listings_Rome.csv')
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2737,https://www.airbnb.com/rooms/2737,20250914152919,2025-09-15,city scrape,"Elif's room in cozy, clean flat.",10 min by bus you can get to Piazza Venezia or...,It used to be an industrial area until late 80...,https://a0.muscache.com/pictures/41225252/e955...,3047,...,5.00,4.40,4.40,NaN,f,6,0,6,0,0.04
1,11834,https://www.airbnb.com/rooms/11834,20250914152919,2025-09-15,city scrape,"Charming Boschetto Studio, Rome",Fantastic apartment in the Monti district. The...,"""Monti"" with its narrow cobblestone alleys, cr...",https://a0.muscache.com/pictures/miso/Hosting-...,44552,...,4.96,4.99,4.81,IT058091C29VJSIZQZ,f,1,1,0,0,1.62
2,12398,https://www.airbnb.com/rooms/12398,20250914152919,2025-09-15,city scrape,Casa Donatello - Home far from Home,Casa Donatello is a newly renovated two-bedroo...,You are at 15 minutes walking distance from hi...,https://a0.muscache.com/pictures/miso/Hosting-...,11756,...,5.00,4.89,4.83,it058091c2kv6epw8f,f,1,1,0,0,0.47
3,19965,https://www.airbnb.com/rooms/19965,20250914152919,2025-09-15,city scrape,S. Peter's Square 5 Min WALK bright and quite ...,AT ONLY 5 MINUTES WALK to S.Peter's Basilica S...,Prati is a famous neighbourhood (rione of Rome...,https://a0.muscache.com/pictures/hosting/Hosti...,75450,...,4.90,4.90,4.54,IT058091C20YD35BX2,t,3,3,0,0,1.07
4,19967,https://www.airbnb.com/rooms/19967,20250914152919,2025-09-15,city scrape,*In front Vatican Museums 2 bedrooms quite bri...,"IN FRONT of the Vatican Museums entrance, at O...",Prati is a famous neighbourhood (rione of Rome...,https://a0.muscache.com/pictures/hosting/Hosti...,75450,...,4.80,4.85,4.28,IT058091C20YD35BX2,t,3,3,0,0,0.32

In [15]:
import pandas as pd
import geopandas as gpd

df_rome =  pd.read_csv('/Users/andreamammano/Data Visualization/DataVisualisationPW_MESA/data/rome/listings_Rome.csv')
geo_rome = gpd.read_file('/Users/andreamammano/Data Visualization/DataVisualisationPW_MESA/data/rome/neighbourhoods_Rome.geojson')
df_rome.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2737,https://www.airbnb.com/rooms/2737,20250914152919,2025-09-15,city scrape,"Elif's room in cozy, clean flat.",10 min by bus you can get to Piazza Venezia or...,It used to be an industrial area until late 80...,https://a0.muscache.com/pictures/41225252/e955...,3047,...,5.00,4.40,4.40,NaN,f,6,0,6,0,0.04
1,11834,https://www.airbnb.com/rooms/11834,20250914152919,2025-09-15,city scrape,"Charming Boschetto Studio, Rome",Fantastic apartment in the Monti district. The...,"""Monti"" with its narrow cobblestone alleys, cr...",https://a0.muscache.com/pictures/miso/Hosting-...,44552,...,4.96,4.99,4.81,IT058091C29VJSIZQZ,f,1,1,0,0,1.62
2,12398,https://www.airbnb.com/rooms/12398,20250914152919,2025-09-15,city scrape,Casa Donatello - Home far from Home,Casa Donatello is a newly renovated two-bedroo...,You are at 15 minutes walking distance from hi...,https://a0.muscache.com/pictures/miso/Hosting-...,11756,...,5.00,4.89,4.83,it058091c2kv6epw8f,f,1,1,0,0,0.47
3,19965,https://www.airbnb.com/rooms/19965,20250914152919,2025-09-15,city scrape,S. Peter's Square 5 Min WALK bright and quite ...,AT ONLY 5 MINUTES WALK to S.Peter's Basilica S...,Prati is a famous neighbourhood (rione of Rome...,https://a0.muscache.com/pictures/hosting/Hosti...,75450,...,4.90,4.90,4.54,IT058091C20YD35BX2,t,3,3,0,0,1.07
4,19967,https://www.airbnb.com/rooms/19967,20250914152919,2025-09-15,city scrape,*In front Vatican Museums 2 bedrooms quite bri...,"IN FRONT of the Vatican Museums entrance, at O...",Prati is a famous neighbourhood (rione of Rome...,https://a0.muscache.com/pictures/hosting/Hosti...,75450,...,4.80,4.85,4.28,IT058091C20YD35BX2,t,3,3,0,0,0.32

In [19]:
df_cop = pd.read_csv('/Users/andreamammano/Data Visualization/DataVisualisationPW_MESA/data/copenhagen/listings_Copenhagen.csv')
geo_cop = gpd.read_file('/Users/andreamammano/Data Visualization/DataVisualisationPW_MESA/data/copenhagen/neighbourhoods_Copenhagen.geojson')
df_cop.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,23500,https://www.airbnb.com/rooms/23500,20250929042231,2025-09-29,city scrape,Nice room - great area (Vesterbro),Nice and cosy room in the heart of Copenhagen ...,NaN,https://a0.muscache.com/pictures/123766/fa4694...,92053,...,5.00,5.00,4.80,NaN,f,2,1,1,0,0.08
1,29118,https://www.airbnb.com/rooms/29118,20250929042231,2025-09-29,city scrape,Best Location in Cool Istedgade,NaN,NaN,https://a0.muscache.com/pictures/b83c7003-367a...,125230,...,5.00,4.84,4.74,NaN,f,1,1,0,0,0.15
2,31094,https://www.airbnb.com/rooms/31094,20250929042231,2025-09-30,previous scrape,"Beautiful, spacious, central, renovated Penthouse","Welcome to our home, we hope you will enjoy Wo...","What else is nearby?<br />To be honest, We thi...",https://a0.muscache.com/pictures/miso/Hosting-...,129976,...,4.82,4.80,4.53,NaN,f,1,1,0,0,0.10
3,32379,https://www.airbnb.com/rooms/32379,20250929042231,2025-09-30,previous scrape,"155 m2 artist flat on Vesterbro, with 2 bathrooms",You enter a narrow entrance and feel the good ...,"Værnedamsvej area is super hip area, we call i...",https://a0.muscache.com/pictures/miso/Hosting-...,140105,...,4.92,4.89,4.71,NaN,f,2,1,1,0,0.47
4,32841,https://www.airbnb.com/rooms/32841,20250929042231,2025-09-29,city scrape,Cozy flat for Adults/Quiet for kids,Our flat is placed in a Central AND Quiet neig...,NaN,https://a0.muscache.com/pictures/28047599/8efd...,142143,...,5.00,4.50,4.50,NaN,f,1,1,0,0,0.04

In [16]:
df_rome.info()

<class 'pandas.DataFrame'>
RangeIndex: 37652 entries, 0 to 37651
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            37652 non-null  int64
 1   listing_url                                   37652 non-null  str
 2   scrape_id                                     37652 non-null  int64
 3   last_scraped                                  37652 non-null  str
 4   source                                        37652 non-null  str
 5   name                                          37652 non-null  str
 6   description                                   36703 non-null  str
 7   neighborhood_overview                         17721 non-null  str
 8   picture_url                                   37652 non-null  str
 9   host_id                                       37652 non-null  int64
 10  host_url                                      37652 non-null  str
 11  host_name                                     37644 non-null  str
 12  host_since                                    37643 non-null  str
 13  host_location                                 27791 non-null  str
 14  host_about                                    17397 non-null  str
 15  host_response_time                            30861 non-null  str
 16  host_response_rate                            30861 non-null  str
 17  host_acceptance_rate                          33814 non-null  str
 18  host_is_superhost                             35456 non-null  str
 19  host_thumbnail_url                            37643 non-null  str
 20  host_picture_url                              37643 non-null  str
 21  host_neighbourhood                            12241 non-null  str
 22  host_listings_count                           37643 non-null  float64
 23  host_total_listings_count                     37643 non-null  float64
 24  host_verifications                            37643 non-null  str
 25  host_has_profile_pic                          37643 non-null  str
 26  host_identity_verified                        37643 non-null  str
 27  neighbourhood                                 17721 non-null  str
 28  neighbourhood_cleansed                        37652 non-null  str
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      37652 non-null  float64
 31  longitude                                     37652 non-null  float64
 32  property_type                                 37652 non-null  str
 33  room_type                                     37652 non-null  str
 34  accommodates                                  37652 non-null  int64
 35  bathrooms                                     33660 non-null  float64
 36  bathrooms_text                                37618 non-null  str
 37  bedrooms                                      36804 non-null  float64
 38  beds                                          33638 non-null  float64
 39  amenities                                     37652 non-null  str
 40  price                                         33564 non-null  str
 41  minimum_nights                                37652 non-null  int64
 42  maximum_nights                                37652 non-null  int64
 43  minimum_minimum_nights                        37631 non-null  float64
 44  maximum_minimum_nights                        37631 non-null  float64
 45  minimum_maximum_nights                        37631 non-null  float64
 46  maximum_maximum_nights                        37631 non-null  float64
 47  minimum_nights_avg_ntm                        37652 non-null  float64
 48  maximum_nights_avg_ntm                        37652 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              37058 non-null  str
 51  availability_30                               37652 non-null  int64
 52  availability_60                               37652 non-null  int64
 53  availability_90                               37652 non-null  int64
 54  availability_365                              37652 non-null  int64
 55  calendar_last_scraped                         37652 non-null  str
 56  number_of_reviews                             37652 non-null  int64
 57  number_of_reviews_ltm                         37652 non-null  int64
 58  number_of_reviews_l30d                        37652 non-null  int64
 59  availability_eoy                              37652 non-null  int64
 60  number_of_reviews_ly                          37652 non-null  int64
 61  estimated_occupancy_l365d                     37652 non-null  int64
 62  estimated_revenue_l365d                       33564 non-null  float64
 63  first_review                                  32255 non-null  str
 64  last_review                                   32255 non-null  str
 65  review_scores_rating                          32255 non-null  float64
 66  review_scores_accuracy                        32253 non-null  float64
 67  review_scores_cleanliness                     32254 non-null  float64
 68  review_scores_checkin                         32253 non-null  float64
 69  review_scores_communication                   32254 non-null  float64
 70  review_scores_location                        32252 non-null  float64
 71  review_scores_value                           32253 non-null  float64
 72  license                                       34589 non-null  str
 73  instant_bookable                              37652 non-null  str
 74  calculated_host_listings_count                37652 non-null  int64
 75  calculated_host_listings_count_entire_homes   37652 non-null  int64
 76  calculated_host_listings_count_private_rooms  37652 non-null  int64
 77  calculated_host_listings_count_shared_rooms   37652 non-null  int64
 78  reviews_per_month                             32255 non-null  float64
dtypes: float64(24), int64(20), str(35)
memory usage: 22.7 MB

In [20]:
df_cop.info()

<class 'pandas.DataFrame'>
RangeIndex: 22994 entries, 0 to 22993
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            22994 non-null  int64
 1   listing_url                                   22994 non-null  str
 2   scrape_id                                     22994 non-null  int64
 3   last_scraped                                  22994 non-null  str
 4   source                                        22994 non-null  str
 5   name                                          22994 non-null  str
 6   description                                   22457 non-null  str
 7   neighborhood_overview                         7985 non-null   str
 8   picture_url                                   22994 non-null  str
 9   host_id                                       22994 non-null  int64
 10  host_url                                      22994 non-null  str
 11  host_name                                     22980 non-null  str
 12  host_since                                    22980 non-null  str
 13  host_location                                 19201 non-null  str
 14  host_about                                    9642 non-null   str
 15  host_response_time                            14626 non-null  str
 16  host_response_rate                            14626 non-null  str
 17  host_acceptance_rate                          17775 non-null  str
 18  host_is_superhost                             22795 non-null  str
 19  host_thumbnail_url                            22980 non-null  str
 20  host_picture_url                              22980 non-null  str
 21  host_neighbourhood                            4933 non-null   str
 22  host_listings_count                           22980 non-null  float64
 23  host_total_listings_count                     22980 non-null  float64
 24  host_verifications                            22980 non-null  str
 25  host_has_profile_pic                          22980 non-null  str
 26  host_identity_verified                        22980 non-null  str
 27  neighbourhood                                 7985 non-null   str
 28  neighbourhood_cleansed                        22994 non-null  str
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      22994 non-null  float64
 31  longitude                                     22994 non-null  float64
 32  property_type                                 22994 non-null  str
 33  room_type                                     22994 non-null  str
 34  accommodates                                  22994 non-null  int64
 35  bathrooms                                     13439 non-null  float64
 36  bathrooms_text                                22988 non-null  str
 37  bedrooms                                      22270 non-null  float64
 38  beds                                          13438 non-null  float64
 39  amenities                                     22994 non-null  str
 40  price                                         13442 non-null  str
 41  minimum_nights                                22994 non-null  int64
 42  maximum_nights                                22994 non-null  int64
 43  minimum_minimum_nights                        22993 non-null  float64
 44  maximum_minimum_nights                        22993 non-null  float64
 45  minimum_maximum_nights                        22993 non-null  float64
 46  maximum_maximum_nights                        22993 non-null  float64
 47  minimum_nights_avg_ntm                        22994 non-null  float64
 48  maximum_nights_avg_ntm                        22994 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              22583 non-null  str
 51  availability_30                               22994 non-null  int64
 52  availability_60                               22994 non-null  int64
 53  availability_90                               22994 non-null  int64
 54  availability_365                              22994 non-null  int64
 55  calendar_last_scraped                         22994 non-null  str
 56  number_of_reviews                             22994 non-null  int64
 57  number_of_reviews_ltm                         22994 non-null  int64
 58  number_of_reviews_l30d                        22994 non-null  int64
 59  availability_eoy                              22994 non-null  int64
 60  number_of_reviews_ly                          22994 non-null  int64
 61  estimated_occupancy_l365d                     22994 non-null  int64
 62  estimated_revenue_l365d                       13442 non-null  float64
 63  first_review                                  20623 non-null  str
 64  last_review                                   20623 non-null  str
 65  review_scores_rating                          20623 non-null  float64
 66  review_scores_accuracy                        20622 non-null  float64
 67  review_scores_cleanliness                     20622 non-null  float64
 68  review_scores_checkin                         20622 non-null  float64
 69  review_scores_communication                   20622 non-null  float64
 70  review_scores_location                        20621 non-null  float64
 71  review_scores_value                           20622 non-null  float64
 72  license                                       0 non-null      float64
 73  instant_bookable                              22994 non-null  str
 74  calculated_host_listings_count                22994 non-null  int64
 75  calculated_host_listings_count_entire_homes   22994 non-null  int64
 76  calculated_host_listings_count_private_rooms  22994 non-null  int64
 77  calculated_host_listings_count_shared_rooms   22994 non-null  int64
 78  reviews_per_month                             20623 non-null  float64
dtypes: float64(25), int64(20), str(34)
memory usage: 13.9 MB

In [ ]:
# 2. Ispezione del dataset degli annunci (Data Understanding)
print("=== ROMA: DIMENSIONE DATASET ===")
print(f"Numero di annunci: {df_rome.shape[0]}")
print(f"Numero di colonne: {df_rome.shape[1]}")

# 3. Il Piano B: Calcoliamo l'Area in km2 dei quartieri dal GeoJSON!
print("\n=== MAPPA DEI QUARTIERI E AREA ===")
# Convertiamo il sistema di coordinate a uno metrico (es. Pseudo-Mercator EPSG:3857) per misurare i metri quadri
geo_rome_metric = geo_rome.to_crs(epsg=3857)
# Calcoliamo l'area in km quadrati (diviso per 1 milione perché i risultati sono in metri quadri)
geo_rome['area_km2'] = geo_rome_metric.geometry.area / 10**6

print(geo_rome[['neighbourhood', 'area_km2']].head())

=== ROMA: DIMENSIONE DATASET ===
Numero di annunci: 37652
Numero di colonne: 79

=== MAPPA DEI QUARTIERI E AREA ===
                neighbourhood    area_km2
0            I Centro Storico   37.083639
1             III Monte Sacro  177.873883
2                IV Tiburtina   88.986442
3         VI Roma delle Torri  206.156656
4  VII San Giovanni/Cinecittà   81.902722

In [21]:
print("\n=== COPENHAGEN: DIMENSIONE DATASET ===")
print(f"Numero di annunci: {df_cop.shape[0]}")
print(f"Numero di colonne: {df_cop.shape[1]}")

print("\n=== MAPPA DEI QUARTIERI E AREA ===")
# Convertiamo il sistema di coordinate a uno metrico (es. Pseudo-Mercator EPSG:3857) per misurare i metri quadri
geo_cop_metric = geo_cop.to_crs(epsg=3857)
# Calcoliamo l'area in km quadrati (diviso per 1 milione perché i risultati sono in metri quadri)
geo_cop['area_km2'] = geo_cop_metric.geometry.area / 10**6

print(geo_cop[['neighbourhood', 'area_km2']].head())

=== COPENHAGEN: DIMENSIONE DATASET ===
Numero di annunci: 22994
Numero di colonne: 79

=== MAPPA DEI QUARTIERI E AREA ===
   neighbourhood   area_km2
0  Frederiksberg  27.324131
1   Brnshj-Husum  27.447904
2        sterbro  30.903570
3       Indre By  32.588012
4        Nrrebro  12.885902